import java.sql.*;
import javax.swing.*;
public class Produto extends javax.swing.JFrame {

    /** Creates new form Produto */
    public Produto() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcodigo = new javax.swing.JLabel();
        jnome = new javax.swing.JTextField();
        jquantidade = new javax.swing.JTextField();
        junidade = new javax.swing.JTextField();
        jtotal = new javax.swing.JTextField();
        jfuncionario = new javax.swing.JComboBox<>();
        jmatricula = new javax.swing.JLabel();
        jconsultar = new javax.swing.JButton();
        jcalcular = new javax.swing.JButton();
        jsalvar = new javax.swing.JButton();
        jeditar = new javax.swing.JButton();
        jexcluir = new javax.swing.JButton();
        jmenu = new javax.swing.JButton();
        jcarregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Produto");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Código");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Quantidade");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Unidade");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Total");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Funcionário");

        jcodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcodigo.setText("jLabel7");

        jfuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jmatricula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jmatricula.setText("jLabel8");

        jconsultar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jconsultar.setText("Consultar");
        jconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconsultarActionPerformed(evt);
            }
        });

        jcalcular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcalcular.setText("Calcular");

        jsalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jsalvar.setText("Salvar");
        jsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsalvarActionPerformed(evt);
            }
        });

        jeditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jeditar.setText("Editar");
        jeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeditarActionPerformed(evt);
            }
        });

        jexcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jexcluir.setText("Excluir");
        jexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexcluirActionPerformed(evt);
            }
        });

        jmenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jmenu.setText("Menu");

        jcarregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcarregar.setText("Carregar");
        jcarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcarregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcodigo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jnome, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jconsultar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(junidade, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jquantidade, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addComponent(jcalcular))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jmatricula))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jsalvar)
                        .addGap(35, 35, 35)
                        .addComponent(jeditar)
                        .addGap(31, 31, 31)
                        .addComponent(jexcluir)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcarregar)
                            .addComponent(jmenu))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcodigo)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jconsultar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(junidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcalcular))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmatricula)
                    .addComponent(jcarregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsalvar)
                    .addComponent(jeditar)
                    .addComponent(jexcluir)
                    .addComponent(jmenu))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsalvarActionPerformed
try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conexao=DriverManager.getConnection
        ("jdbc:mysql://localhost/aula17","root","");
        Statement sql=conexao.createStatement();
        
        
    }  
    catch(ClassNotFoundException e){
        JOptionPane.showMessageDialog
        (this,"Erro na conexão" + e.getMessage());
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog
        (this,"Erro na linguagem" + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jsalvarActionPerformed

    private void jeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeditarActionPerformed
try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conexao=DriverManager.getConnection
        ("jdbc:mysql://localhost/aula17","root","");
        Statement sql=conexao.createStatement();
        
        
    }  
    catch(ClassNotFoundException e){
        JOptionPane.showMessageDialog
        (this,"Erro na conexão" + e.getMessage());
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog
        (this,"Erro na linguagem" + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jeditarActionPerformed

    private void jexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexcluirActionPerformed
try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conexao=DriverManager.getConnection
        ("jdbc:mysql://localhost/aula17","root","");
        Statement sql=conexao.createStatement();
        
        
    }  
    catch(ClassNotFoundException e){
        JOptionPane.showMessageDialog
        (this,"Erro na conexão" + e.getMessage());
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog
        (this,"Erro na linguagem" + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jexcluirActionPerformed

    private void jcarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcarregarActionPerformed
try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conexao=DriverManager.getConnection
        ("jdbc:mysql://localhost/aula17","root","");
        Statement sql=conexao.createStatement();
        
        
    }  
    catch(ClassNotFoundException e){
        JOptionPane.showMessageDialog
        (this,"Erro na conexão" + e.getMessage());
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog
        (this,"Erro na linguagem" + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jcarregarActionPerformed

    private void jconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconsultarActionPerformed
try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conexao=DriverManager.getConnection
        ("jdbc:mysql://localhost/aula17","root","");
        Statement sql=conexao.createStatement();
        
        
    }  
    catch(ClassNotFoundException e){
        JOptionPane.showMessageDialog
        (this,"Erro na conexão" + e.getMessage());
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog
        (this,"Erro na linguagem" + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jconsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jcalcular;
    private javax.swing.JButton jcarregar;
    private javax.swing.JLabel jcodigo;
    private javax.swing.JButton jconsultar;
    private javax.swing.JButton jeditar;
    private javax.swing.JButton jexcluir;
    private javax.swing.JComboBox<String> jfuncionario;
    private javax.swing.JLabel jmatricula;
    private javax.swing.JButton jmenu;
    private javax.swing.JTextField jnome;
    private javax.swing.JTextField jquantidade;
    private javax.swing.JButton jsalvar;
    private javax.swing.JTextField jtotal;
    private javax.swing.JTextField junidade;
    // End of variables declaration//GEN-END:variables

}
