import java.sql.*;
import javax.swing.*;
public class Funcionario extends javax.swing.JFrame {
    public void limpacampo()
    {
        jnome.setText("");
        jcpf.setText("");
        jemail.setText("");
        jcpf.requestFocus();
    }

    /**
     * Creates new form Funcionario
     */
    public Funcionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jnome = new javax.swing.JTextField();
        jemail = new javax.swing.JTextField();
        jcpf = new javax.swing.JFormattedTextField();
        jmatricula = new javax.swing.JLabel();
        jsalvar = new javax.swing.JButton();
        jeditar = new javax.swing.JButton();
        jexcluir = new javax.swing.JButton();
        jconsultar = new javax.swing.JButton();
        jmenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Funcionário");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Matrícula");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("CPF");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nome");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("E-mail");

        jnome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        try {
            jcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jcpf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jmatricula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jsalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jsalvar.setText("Salvar");
        jsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsalvarActionPerformed(evt);
            }
        });

        jeditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jeditar.setText("Editar");
        jeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeditarActionPerformed(evt);
            }
        });

        jexcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jexcluir.setText("Excluir");
        jexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexcluirActionPerformed(evt);
            }
        });

        jconsultar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jconsultar.setText("Consultar");
        jconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconsultarActionPerformed(evt);
            }
        });

        jmenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jmenu.setText("Menu");
        jmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jsalvar)
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jmatricula)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jnome)
                            .addComponent(jemail)
                            .addComponent(jcpf, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jconsultar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jeditar)
                        .addGap(18, 18, 18)
                        .addComponent(jexcluir)
                        .addGap(30, 30, 30)
                        .addComponent(jmenu)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jmatricula))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jconsultar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsalvar)
                    .addComponent(jexcluir)
                    .addComponent(jmenu)
                    .addComponent(jeditar))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsalvarActionPerformed
try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conexao=DriverManager.getConnection
        ("jdbc:mysql://localhost/aula17","root","");
        Statement sql=conexao.createStatement();
        
        String cpf=jcpf.getText();
        String nome=jnome.getText();
        String email=jemail.getText();
        sql.executeUpdate("insert into funcionario (cpf,nome,email)values('"+cpf+"','"+nome+"','"+email+"')");
        JOptionPane.showMessageDialog(this,"Cadastrado com sucesso");
        limpacampo();
    }  
    catch(ClassNotFoundException e){
        JOptionPane.showMessageDialog
        (this,"Erro na conexão" + e.getMessage());
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog
        (this,"Erro na linguagem" + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jsalvarActionPerformed

    private void jeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeditarActionPerformed
try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conexao=DriverManager.getConnection
        ("jdbc:mysql://localhost/aula17","root","");
        Statement sql=conexao.createStatement();
        
        String cpf=jcpf.getText();
        String nome=jnome.getText();
        String email=jemail.getText();
        
        int registro=sql.executeUpdate("update funcionario set nome='"+nome+"',email='"+email+" where 'cpf='"+cpf+"'");
        
        if(registro!=0)
        {
            JOptionPane.showMessageDialog(this,"Dados Alterados");
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Dados não Alterados");
        }
    }  
    catch(ClassNotFoundException e){
        JOptionPane.showMessageDialog
        (this,"Erro na conexão" + e.getMessage());
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog
        (this,"Erro na linguagem" + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jeditarActionPerformed

    private void jconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconsultarActionPerformed
        boolean consulta=true;
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conexao=DriverManager.getConnection
        ("jdbc:mysql://localhost/aula17","root","");
        Statement sql=conexao.createStatement();
        
        String cpf=jcpf.getText();
        ResultSet linha=sql.executeQuery("select * from funcionario where cpf='"+cpf+"'");
        
        while(linha.next())
        {
            int matricula=linha.getInt("matricula");
            jmatricula.setText(String.valueOf(matricula));
            jcpf.setText(linha.getString("cpf"));
            jnome.setText(linha.getString("nome"));
            jemail.setText(linha.getString("email"));
            
            consulta=false;
            JOptionPane.showMessageDialog(this,"Dados encontrados" );
        }
        if (consulta)
        {
            JOptionPane.showMessageDialog(this,"Dados não encontrados" );
            limpacampo();
        }
        
    }  
    catch(ClassNotFoundException e){
        JOptionPane.showMessageDialog
        (this,"Erro na conexão" + e.getMessage());
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog
        (this,"Erro na linguagem" + e.getMessage());
    }    // TODO add your handling code here:
    }//GEN-LAST:event_jconsultarActionPerformed

    private void jexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexcluirActionPerformed
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conexao=DriverManager.getConnection
        ("jdbc:mysql://localhost/aula17","root","");
        Statement sql=conexao.createStatement();
        
        String cpf=jcpf.getText();
        
        int registro=sql.executeUpdate("delete from funcionario where cpf='"+cpf+"'");
        
        if(registro!=0)
        {
             JOptionPane.showMessageDialog(this,"Dados excluídos");
             limpacampo();
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Dados não excluídos");
        }
        
    }  
    catch(ClassNotFoundException e){
        JOptionPane.showMessageDialog
        (this,"Erro na conexão" + e.getMessage());
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog
        (this,"Erro na linguagem" + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jexcluirActionPerformed

    private void jmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuActionPerformed
            new Menu().setVisible(true);
            this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jconsultar;
    private javax.swing.JFormattedTextField jcpf;
    private javax.swing.JButton jeditar;
    private javax.swing.JTextField jemail;
    private javax.swing.JButton jexcluir;
    private javax.swing.JLabel jmatricula;
    private javax.swing.JButton jmenu;
    private javax.swing.JTextField jnome;
    private javax.swing.JButton jsalvar;
    // End of variables declaration//GEN-END:variables
}
