import java.sql.*;
import javax.swing.*;
public class Produto extends javax.swing.JFrame {

      public void limpacampo()
    {
        jnome.setText("");
        jquantidade.setText("");
        junidade.setText("");
        jtotal.setText("");
        jnome.requestFocus();
    }

    /** Creates new form Produto */
    public Produto() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jnome = new javax.swing.JTextField();
        jquantidade = new javax.swing.JTextField();
        junidade = new javax.swing.JTextField();
        jtotal = new javax.swing.JTextField();
        jfuncionario = new javax.swing.JComboBox<>();
        jmatricula = new javax.swing.JLabel();
        jconsultar = new javax.swing.JButton();
        jcalcular = new javax.swing.JButton();
        jsalvar = new javax.swing.JButton();
        jeditar = new javax.swing.JButton();
        jexcluir = new javax.swing.JButton();
        jmenu = new javax.swing.JButton();
        jcarregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Produto");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Código");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Quantidade");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Unidade");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Total");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Funcionário");

        jfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfuncionarioActionPerformed(evt);
            }
        });

        jmatricula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jconsultar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jconsultar.setText("Consultar");
        jconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconsultarActionPerformed(evt);
            }
        });

        jcalcular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcalcular.setText("Calcular");
        jcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcalcularActionPerformed(evt);
            }
        });

        jsalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jsalvar.setText("Salvar");
        jsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsalvarActionPerformed(evt);
            }
        });

        jeditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jeditar.setText("Editar");
        jeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeditarActionPerformed(evt);
            }
        });

        jexcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jexcluir.setText("Excluir");
        jexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexcluirActionPerformed(evt);
            }
        });

        jmenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jmenu.setText("Menu");
        jmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuActionPerformed(evt);
            }
        });

        jcarregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcarregar.setText("Carregar");
        jcarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcarregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jfuncionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jmatricula)
                                .addGap(18, 18, 18)
                                .addComponent(jcarregar)
                                .addGap(86, 86, 86))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jnome, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jconsultar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jtotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                            .addComponent(junidade, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jquantidade, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addComponent(jcalcular)))
                                .addGap(0, 108, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jsalvar)
                        .addGap(35, 35, 35)
                        .addComponent(jeditar)
                        .addGap(31, 31, 31)
                        .addComponent(jexcluir)
                        .addGap(44, 44, 44)
                        .addComponent(jmenu)))
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jconsultar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(junidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcalcular))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcarregar)
                    .addComponent(jmatricula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsalvar)
                    .addComponent(jeditar)
                    .addComponent(jexcluir)
                    .addComponent(jmenu))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsalvarActionPerformed
try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conexao=DriverManager.getConnection
        ("jdbc:mysql://localhost/aula17","root","");
        Statement sql=conexao.createStatement();
        String nome=jnome.getText();
        String quantidade=jquantidade.getText();
        String unidade=junidade.getText();
        String total=jtotal.getText();
        
      
        sql.executeUpdate("insert into produto (nome,quantidade,unidade,total)values('"+nome+"','"+quantidade+"','"+unidade+"','"+total+"')");
        JOptionPane.showMessageDialog(this,"Cadastrado com sucesso");
        limpacampo();
        
        
    }  
    catch(ClassNotFoundException e){
        JOptionPane.showMessageDialog
        (this,"Erro na conexão" + e.getMessage());
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog
        (this,"Erro na linguagem" + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jsalvarActionPerformed

    private void jeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeditarActionPerformed
try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conexao=DriverManager.getConnection
        ("jdbc:mysql://localhost/aula17","root","");
        Statement sql=conexao.createStatement();
        
        String nome=jnome.getText();
        String quantidade=jquantidade.getText();
        String unidade=junidade.getText();
        String total=jtotal.getText();
        
        int registro=sql.executeUpdate("update funcionario set nome='"+nome+"',quantidade='"+quantidade+"',unidade='"+unidade+"',total='"+total+"'");
        
        if(registro!=0)
        {
            JOptionPane.showMessageDialog(this,"Dados Alterados");
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Dados não Alterados");
        }
    }  
        
    catch(ClassNotFoundException e){
        JOptionPane.showMessageDialog
        (this,"Erro na conexão" + e.getMessage());
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog
        (this,"Erro na linguagem" + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jeditarActionPerformed

    private void jexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexcluirActionPerformed
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conexao=DriverManager.getConnection
        ("jdbc:mysql://localhost/aula17","root","");
        Statement sql=conexao.createStatement();
        
        String nome=jnome.getText();
        
        int registro=sql.executeUpdate("delete from produto where nome='"+nome+"'");
        
        if(registro!=0)
        {
             JOptionPane.showMessageDialog(this,"Dados excluídos");
             limpacampo();
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Dados não excluídos");
        }
        
    }  
    catch(ClassNotFoundException e){
        JOptionPane.showMessageDialog
        (this,"Erro na conexão" + e.getMessage());
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog
        (this,"Erro na linguagem" + e.getMessage());
    }   // TODO add your handling code here:
    }//GEN-LAST:event_jexcluirActionPerformed

    private void jcarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcarregarActionPerformed
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conexao=DriverManager.getConnection
        ("jdbc:mysql://localhost/aula17","root","");
        Statement sql=conexao.createStatement();
        
        ResultSet linha=sql.executeQuery("select * from funcionario");
        while(linha.next()){
            jfuncionario.addItem(linha.getString("nome"));    
        }
        /*ResultSet consulta=sql.executeQuery("select matricula from funcionario where nome='"+jfuncionario.getSelectedItem()+"'");
        while(consulta.next()){
            jmatricula.setText(consulta.getString("matricula"));
        }   */
        
        }  
        catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog
            (this,"Erro na conexão" + e.getMessage());
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog
            (this,"Erro na linguagem" + e.getMessage());
        }                   
            // TODO add your handling code here:
    }//GEN-LAST:event_jcarregarActionPerformed

    private void jconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconsultarActionPerformed
 boolean consulta=true;
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conexao=DriverManager.getConnection
        ("jdbc:mysql://localhost/aula17","root","");
        Statement sql=conexao.createStatement();
        
        String nome=jnome.getText();
        ResultSet linha=sql.executeQuery("select * from produto where jnome='"+nome+"'");
        
        while(linha.next())
        {   
            jnome.setText(linha.getString("nome"));
            jquantidade.setText(linha.getString("quantidade"));
            junidade.setText(linha.getString("unidade"));
            jtotal.setText(linha.getString("total"));
            int matricula=linha.getInt("matricula");
            jmatricula.setText(String.valueOf(matricula));
           
            
            consulta=false;
            JOptionPane.showMessageDialog(this,"Dados encontrados" );
        }
        if (consulta)
        {
            JOptionPane.showMessageDialog(this,"Dados não encontrados" );
            limpacampo();
        }
        
    }  
    catch(ClassNotFoundException e){
        JOptionPane.showMessageDialog
        (this,"Erro na conexão" + e.getMessage());
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog
        (this,"Erro na linguagem" + e.getMessage());
    }                                              
       // TODO add your handling code here:
    }//GEN-LAST:event_jconsultarActionPerformed

    private void jmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuActionPerformed
            new Menu().setVisible(true);
            this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jmenuActionPerformed

    private void jcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcalcularActionPerformed
                                         
        int quantidade=Integer.parseInt(jquantidade.getText());
        double unidade=Double.parseDouble(junidade.getText());
        double total = (quantidade * unidade);
        jtotal.setText(String.valueOf(total));
                                                // TODO add your handling code here:
    }//GEN-LAST:event_jcalcularActionPerformed

    private void jfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfuncionarioActionPerformed
     try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conexao=DriverManager.getConnection
        ("jdbc:mysql://localhost/aula17","root","");
        Statement sql=conexao.createStatement();
        
        /*ResultSet linha=sql.executeQuery("select * from funcionario");
        while(linha.next()){
            jfuncionario.addItem(linha.getString("nome"));   
        }*/ 
        ResultSet consulta=sql.executeQuery("select matricula from funcionario where nome='"+jfuncionario.getSelectedItem()+"'");
        while(consulta.next()){
            jmatricula.setText(consulta.getString("matricula"));
        }   
        
        }  
        catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog
            (this,"Erro na conexão" + e.getMessage());
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog
            (this,"Erro na linguagem" + e.getMessage());
        }                   
              // TODO add your handling code here:
    }//GEN-LAST:event_jfuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jcalcular;
    private javax.swing.JButton jcarregar;
    private javax.swing.JButton jconsultar;
    private javax.swing.JButton jeditar;
    private javax.swing.JButton jexcluir;
    private javax.swing.JComboBox<String> jfuncionario;
    private javax.swing.JLabel jmatricula;
    private javax.swing.JButton jmenu;
    private javax.swing.JTextField jnome;
    private javax.swing.JTextField jquantidade;
    private javax.swing.JButton jsalvar;
    private javax.swing.JTextField jtotal;
    private javax.swing.JTextField junidade;
    // End of variables declaration//GEN-END:variables

}
