
create DATABASE locadoraBD;
	use locadoraBD;
		CREATE TABLE CATEGORIA (
			CODIGO INT AUTO_INCREMENT PRIMARY KEY,
			CLASSE VARCHAR(255) NOT NULL,
			VALOR_DIARIA DOUBLE NOT NULL
			);
            
		CREATE TABLE VEICULO (
			CHASSI VARCHAR(255) not null UNIQUE,
			PLACA VARCHAR(255) NOT NULL PRIMARY KEY,
            MODELO VARCHAR(255) NOT NULL,
            COR VARCHAR(255) NOT NULL,
            ANO INT NOT NULL,
            CODIGOFK INT NOT NULL UNIQUE,
            
            FOREIGN KEY (CODIGOFK) REFERENCES CATEGORIA (CODIGO)
            );
            
		CREATE TABLE CLIENTE (
			CNH_CLIENTE VARCHAR(20) PRIMARY KEY,
			NOME_CLIENTE VARCHAR(255) NOT NULL,
			IDADE_CLIENTE INT NOT NULL,
			ENDERECO_CLIENTE VARCHAR(255) NOT NULL,
			RG_CLIENTE VARCHAR(20) NOT NULL UNIQUE
			);
            
        
            
		CREATE TABLE ALUGA (
			DATA_ALUGUEL DATE NOT NULL,
            HORA_ALUGUEL TIME NOT NULL,
			ID_ALUGUEL INT AUTO_INCREMENT PRIMARY KEY, 
            CNH_CLIENTEFK VARCHAR(20) NOT NULL ,
            PLACAFK VARCHAR(255) NOT NULL,
            
            FOREIGN KEY (CNH_CLIENTEFK) REFERENCES CLIENTE (CNH_CLIENTE),
            
				FOREIGN KEY (PLACAFK) REFERENCES VEICULO (PLACA)
			);
            
